# -*- coding: utf-8 -*-
"""EDA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FaE0Z0TvSzgBEb0vk8EFk5Np6nazZWdv

Import Libraries
"""

import pandas as pd
import sys, subprocess, pkgutil
import os, re, json
from pathlib import Path
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from itertools import combinations
from scipy.stats import chi2_contingency
import os, warnings, numpy as np, pandas as pd, matplotlib.pyplot as plt
warnings.filterwarnings("ignore")

from sklearn.model_selection import train_test_split, GridSearchCV, learning_curve, validation_curve
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.pipeline import Pipeline
from sklearn.svm import LinearSVC
from sklearn.calibration import CalibratedClassifierCV
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix, roc_curve, auc, roc_auc_score
from sklearn.preprocessing import label_binarize

"""Load Dataset"""

df = pd.read_csv("/content/drive/MyDrive/MerntalDisorder.csv")

print("---- First 5 Rows ----")
print(df.head())

print("\n---- Dataset Shape ----")
print("Columns:", df.shape[1])

"""Exploratory data analysis"""

OUT_DIR   = "/content/eda_reports"

COMMENT_COL  = None
RESPONSE_COL = None
STAGE_COL    = None
CLASS_COL    = None
CATEGORY_COL = None
SUBTYPE_COL  = None

def _pip_install(pkgs):
    for p in pkgs:
        if pkgutil.find_loader(p.split("==")[0].split(">=")[0]) is None:
            subprocess.check_call([sys.executable, "-m", "pip", "install", p])

_pip_install([
    "pandas>=2.2.0",
    "numpy>=1.26.0",
    "matplotlib>=3.8.0",
    "scipy>=1.10.0",
    "scikit-learn>=1.4.0",
])


BN_RANGE = re.compile(r'[\u0980-\u09FF]')
EMAIL_RE  = re.compile(r'\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}\b')
PHONE_RE  = re.compile(r'(?<!\d)(?:\+?\d[\d\-\s]{8,}\d)(?!\d)')
URL_RE    = re.compile(r'(https?://\S+|www\.\S+)', re.IGNORECASE)
STAGE_SET = {"হালকা","মাঝারি","তীব্র","mild","moderate","severe"}

def safe_mkdir(p: Path):
    p.mkdir(parents=True, exist_ok=True)

def read_csv_any(path: str) -> pd.DataFrame:
    try:
        return pd.read_csv(path)
    except UnicodeDecodeError:
        return pd.read_csv(path, encoding="utf-8-sig")

def is_bangla_ratio(text: str) -> float:
    if not isinstance(text, str) or not text.strip(): return 0.0
    return len(BN_RANGE.findall(text)) / max(len(text), 1)

def text_features(s: pd.Series, prefix: str) -> pd.DataFrame:
    x = s.fillna("").astype(str)
    df = pd.DataFrame({
        f"{prefix}_len": x.str.len(),
        f"{prefix}_words": x.str.split().map(len),
        f"{prefix}_bangla_ratio": x.map(is_bangla_ratio),
        f"{prefix}_has_email": x.str.contains(EMAIL_RE).astype(int),
        f"{prefix}_has_phone": x.str.contains(PHONE_RE).astype(int),
        f"{prefix}_has_url": x.str.contains(URL_RE).astype(int),
        f"{prefix}_exclam": x.str.count("!"),
        f"{prefix}_qmark": x.str.count(r"\?"),
        f"{prefix}_comma": x.str.count(","),
        f"{prefix}_dot": x.str.count("।") + x.str.count(r"\."),
    })
    return df

def guess_col(df: pd.DataFrame, candidates):
    lower = {c.lower(): c for c in df.columns}
    for c in candidates:
        if c.lower() in lower:
            return lower[c.lower()]

    if any(k in candidates[0].lower() for k in ["comment","response","মন্তব্য","কমেন্ট","উত্তর","প্রতিক্রিয়া"]):
        obj_cols = [c for c in df.columns if df[c].dtype == "object"]
        if obj_cols:
            lens = {c: df[c].dropna().astype(str).str.len().mean() for c in obj_cols}
            return max(lens, key=lens.get) if lens else None
    return None


def pearson_num(x: pd.Series, y: pd.Series) -> float:
    a = pd.to_numeric(x, errors="coerce"); b = pd.to_numeric(y, errors="coerce")
    mask = ~(a.isna() | b.isna())
    if mask.sum() < 3: return np.nan
    return float(np.corrcoef(a[mask], b[mask])[0,1])

def cramers_v_corrected(x: pd.Series, y: pd.Series) -> float:
    tbl = pd.crosstab(x, y)
    if tbl.size == 0: return np.nan
    chi2, _, _, _ = chi2_contingency(tbl, correction=False)
    n = tbl.values.sum()
    if n == 0: return np.nan
    phi2 = chi2 / n
    r, k = tbl.shape
    phi2corr = max(0, phi2 - ((k-1)*(r-1))/(n-1))
    rcorr = r - ((r-1)**2)/(n-1)
    kcorr = k - ((k-1)**2)/(n-1)
    denom = min((kcorr-1), (rcorr-1))
    if denom <= 0: return np.nan
    return float(np.sqrt(phi2corr / denom))

def correlation_ratio(categories: pd.Series, measurements: pd.Series) -> float:
    try:
        cats = categories.astype("category").cat.codes.values
        y = pd.to_numeric(measurements, errors="coerce").values
        mask = ~np.isnan(y)
        cats, y = cats[mask], y[mask]
        if len(y) == 0: return np.nan
        y_mean = y.mean()
        classes = np.unique(cats)
        ss_between = 0.0
        for c in classes:
            y_c = y[cats == c]
            if len(y_c) == 0: continue
            ss_between += len(y_c) * (y_c.mean() - y_mean) ** 2
        ss_total = ((y - y_mean) ** 2).sum()
        return float(np.sqrt(ss_between / ss_total)) if ss_total > 0 else np.nan
    except Exception:
        return np.nan

def mixed_correlation(df: pd.DataFrame, num_cols, cat_cols) -> pd.DataFrame:
    cols = num_cols + cat_cols
    M = pd.DataFrame(np.nan, index=cols, columns=cols)
    # numeric-numeric
    for i, c1 in enumerate(num_cols):
        M.loc[c1, c1] = 1.0
        for c2 in num_cols[i+1:]:
            r = pearson_num(df[c1], df[c2])
            M.loc[c1, c2] = M.loc[c2, c1] = r
    # categorical-categorical
    for i, c1 in enumerate(cat_cols):
        M.loc[c1, c1] = 1.0
        for c2 in cat_cols[i+1:]:
            v = cramers_v_corrected(df[c1].astype(str), df[c2].astype(str))
            M.loc[c1, c2] = M.loc[c2, c1] = v
    # categorical-numeric (η)
    for c in cat_cols:
        for n in num_cols:
            eta = correlation_ratio(df[c].astype(str), df[n])
            M.loc[c, n] = M.loc[n, c] = eta
    return M

def plot_heatmap(matrix: pd.DataFrame, out_png: Path, title: str):
    fig, ax = plt.subplots(figsize=(max(8, len(matrix.columns)*0.6), max(6, len(matrix.index)*0.6)))
    im = ax.imshow(matrix.values, vmin=-1, vmax=1, aspect='auto')
    ax.set_xticks(range(len(matrix.columns)))
    ax.set_yticks(range(len(matrix.index)))
    ax.set_xticklabels(matrix.columns, rotation=90)
    ax.set_yticklabels(matrix.index)
    ax.set_title(title)
    cbar = plt.colorbar(im)
    cbar.set_label("corr / Cramér’s V / η")
    plt.tight_layout()
    plt.savefig(out_png, dpi=180)
    plt.show()
    plt.close()

# ------------------------ MAIN EDA ---------------------------
def run_eda(input_csv: str, out_dir: str,
            comment_col=None, response_col=None,
            stage_col=None, class_col=None,
            category_col=None, subtype_col=None):
    outdir = Path(out_dir)
    safe_mkdir(outdir)

    df = read_csv_any(input_csv)
    df["__source_file"] = os.path.basename(input_csv)

    # Resolve columns (auto if None)
    comment_col = comment_col or guess_col(df, ["comment_bn","comment","comments","text","content","message","মন্তব্য","কমেন্ট"])
    response_col = response_col or guess_col(df, ["response_bn","response","reply","উত্তর","প্রতিক্রিয়া"])
    stage_col    = stage_col    or guess_col(df, ["stage_bn","stage","severity","স্টেজ","স্তর"])
    class_col    = class_col    or guess_col(df, ["class_bn","class","label","topic_key","টপিক","ক্লাস","শ্রেণী"])
    category_col = category_col or guess_col(df, ["category_bn","category","ক্যাটাগরি","ধরণ"])
    subtype_col  = subtype_col  or guess_col(df, ["subtype_bn","subtype","sub_class","সাবটাইপ"])

    resolved = {
        "comment_col": comment_col,
        "response_col": response_col,
        "stage_col": stage_col,
        "class_col": class_col,
        "category_col": category_col,
        "subtype_col": subtype_col
    }
    with open(outdir / "resolved_columns.json", "w", encoding="utf-8") as f:
        json.dump(resolved, f, ensure_ascii=False, indent=2)

    # Basic cleaning
    if comment_col and comment_col in df.columns:
        df = df[df[comment_col].astype(str).str.strip().str.len() > 0]
    if response_col and response_col in df.columns:
        df = df[df[response_col].astype(str).str.strip().str.len() > 0]

    df.to_csv(outdir / "cleaned.csv", index=False, encoding="utf-8-sig")

    # Text numeric features
    num_blocks = []
    if comment_col:  num_blocks.append(text_features(df[comment_col], "comment"))
    if response_col: num_blocks.append(text_features(df[response_col], "response"))
    num_df = pd.concat(num_blocks, axis=1) if num_blocks else pd.DataFrame()
    if not num_df.empty:
        num_df.to_csv(outdir / "text_numeric_features.csv", index=False, encoding="utf-8-sig")

    # Quick counts + bar plots
    def value_counts_plot(col, title, fname):
        if not col or col not in df.columns: return
        vc = df[col].astype(str).value_counts().head(20)
        vc.to_csv(outdir / f"value_counts_{fname}.csv", encoding="utf-8-sig")
        try:
            plt.figure()
            vc.plot(kind="bar")
            plt.title(title); plt.tight_layout()
            p = outdir / f"plot_{fname}.png"
            plt.savefig(p, dpi=160); plt.show(); plt.close()
        except Exception:
            pass

    value_counts_plot(stage_col, "Stage distribution", "stage")
    value_counts_plot(class_col, "Class (Top-20)", "class")
    value_counts_plot(category_col, "Category (Top-20)", "category")
    value_counts_plot(subtype_col, "Subtype (Top-20)", "subtype")

    # Crosstabs (row-normalized)
    def crosstab_norm(rcol, ccol, fname):
        if not rcol or not ccol: return
        if rcol not in df.columns or ccol not in df.columns: return
        tab = pd.crosstab(df[rcol].astype(str), df[ccol].astype(str), normalize="index")
        tab.to_csv(outdir / fname, encoding="utf-8-sig")

    crosstab_norm(stage_col, class_col, "stage_by_class.csv")
    crosstab_norm(stage_col, category_col, "stage_by_category.csv")
    crosstab_norm(stage_col, subtype_col, "stage_by_subtype.csv")

    # Build matrix-ready DF
    matrix_df = pd.DataFrame(index=df.index)
    if not num_df.empty:
        matrix_df = pd.concat([matrix_df, num_df], axis=1)
    cat_cols = [c for c in [stage_col, class_col, category_col, subtype_col, "__source_file"] if c and c in df.columns]
    for c in cat_cols:
        matrix_df[c] = df[c].astype(str)

    numeric_cols = [c for c in matrix_df.columns if matrix_df[c].dtype != 'O']
    categorical_cols = [c for c in matrix_df.columns if c not in numeric_cols]

    # Mixed correlation + heatmap
    if len(numeric_cols) + len(categorical_cols) > 0:
        M = mixed_correlation(matrix_df, numeric_cols, categorical_cols)
        M.to_csv(outdir / "correlation_matrix_mixed.csv", encoding="utf-8-sig")
        plot_heatmap(M, outdir / "correlation_matrix_mixed.png",
                     "Mixed Correlation (Pearson / Cramér’s V / η)")

    # PII/links quick scan
    pii = {}
    if comment_col:
        s = df[comment_col].astype(str)
        pii["comment_has_email"] = int(s.str.contains(EMAIL_RE).sum())
        pii["comment_has_phone"] = int(s.str.contains(PHONE_RE).sum())
        pii["comment_has_url"]   = int(s.str.contains(URL_RE).sum())
    if response_col:
        s = df[response_col].astype(str)
        pii["response_has_email"] = int(s.str.contains(EMAIL_RE).sum())
        pii["response_has_phone"] = int(s.str.contains(PHONE_RE).sum())
        pii["response_has_url"]   = int(s.str.contains(URL_RE).sum())

    # Stage sanity
    stage_unexpected = 0
    if stage_col and stage_col in df.columns:
        st_bad = ~df[stage_col].astype(str).str.strip().str.lower().isin({s.lower() for s in STAGE_SET})
        stage_unexpected = int(st_bad.sum())

    summary = {
        "input_csv": input_csv,
        "rows": int(len(df)),
        "columns": list(df.columns),
        "resolved_columns": resolved,
        "numeric_features": numeric_cols if len(numeric_cols) else [],
        "categorical_features": categorical_cols if len(categorical_cols) else [],
        "stage_unexpected_count": stage_unexpected,
        "pii_scan": pii
    }
    with open(outdir / "summary.json", "w", encoding="utf-8") as f:
        json.dump(summary, f, ensure_ascii=False, indent=2)

    print("[OK] EDA complete.")
    print("Outputs saved in:", str(outdir.resolve()))

# ------------------------ RUN NOW ----------------------------
run_eda(
    input_csv=INPUT_CSV,
    out_dir=OUT_DIR,
    comment_col=COMMENT_COL,
    response_col=RESPONSE_COL,
    stage_col=STAGE_COL,
    class_col=CLASS_COL,
    category_col=CATEGORY_COL,
    subtype_col=SUBTYPE_COL
)