# -*- coding: utf-8 -*-
"""Training_Mental_Health.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FaE0Z0TvSzgBEb0vk8EFk5Np6nazZWdv

Import Libraries
"""

import pandas as pd
import sys, subprocess, pkgutil
import os, re, json
from pathlib import Path
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from itertools import combinations
from scipy.stats import chi2_contingency
import os, warnings, numpy as np, pandas as pd, matplotlib.pyplot as plt
warnings.filterwarnings("ignore")

from sklearn.model_selection import train_test_split, GridSearchCV, learning_curve, validation_curve
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.pipeline import Pipeline
from sklearn.svm import LinearSVC
from sklearn.calibration import CalibratedClassifierCV
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix, roc_curve, auc, roc_auc_score
from sklearn.preprocessing import label_binarize

"""Load Dataset"""

df = pd.read_csv("/content/drive/MyDrive/MerntalDisorder.csv")

print("---- First 5 Rows ----")
print(df.head())

print("\n---- Dataset Shape ----")
print("Columns:", df.shape[1])

"""Exploratory data analysis

Model Training and Evauation
"""

keep_cols = ['id','category_bn','comment_bn','response_bn','class']
present   = [c for c in keep_cols if c in df.columns]
df        = df.drop(columns=[c for c in df.columns if c not in present], errors="ignore").copy()

df['comment_bn'] = df['comment_bn'].fillna('').astype(str)
df = df[df['comment_bn'].str.strip()!=''].drop_duplicates(subset=['comment_bn'])

df['class'] = df.get('class', pd.Series(index=df.index)).fillna('অনির্দিষ্ট').astype(str)

X = df['comment_bn']
y = df['class'].astype(str)

X_tr, X_te, y_tr, y_te = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

def make_calibrated_pipeline(max_feat=80000):
    tfidf = TfidfVectorizer(
        max_features=max_feat, ngram_range=(1,2), analyzer='word',
        min_df=2, sublinear_tf=True
    )

    clf = CalibratedClassifierCV(
        estimator=LinearSVC(class_weight='balanced'),
        method='sigmoid', cv=3
    )
    return Pipeline([('tfidf', tfidf), ('clf', clf)])

pipe = make_calibrated_pipeline(80000)

param_grid = {
    'tfidf__ngram_range': [(1,1),(1,2)],
    'tfidf__max_features': [40000, 80000],
    'clf__estimator__C': [0.5, 1.0, 2.0],  # path into inner LinearSVC
}

gs = GridSearchCV(pipe, param_grid, cv=3, n_jobs=-1, scoring='f1_weighted', verbose=0)
print("Training CLASS model (Calibrated LinearSVC + TF-IDF)...")
gs.fit(X_tr, y_tr)
print("Best params (class):", gs.best_params_)
best = gs.best_estimator_

y_hat = best.predict(X_te)
print("\n=== CLASS REPORT ===")
print(classification_report(y_te, y_hat, zero_division=0))
print("Accuracy:", round(accuracy_score(y_te, y_hat), 4))